USE CTSDB;

SELECT * FROM Employee;

SELECT Name,Salary,ROW_NUMBER() OVER(ORDER BY Salary DESC) AS RowNo FROM Employee;

SELECT Name,Salary,RANK() OVER(ORDER BY Salary DESC) AS Rnk FROM Employee;

SELECT Name,Salary,DENSE_RANK() OVER(ORDER BY Salary DESC) AS DRnk FROM Employee;

SELECT Name,Dept,Salary,ROW_NUMBER() OVER(PARTITION BY Dept ORDER BY Salary DESC) AS No FROM Employee;

WITH A AS (SELECT * FROM Employee WHERE Salary>30000) SELECT * FROM A;

WITH RECURSIVE N AS (SELECT 1 AS No UNION ALL SELECT No+1 FROM N WHERE No<5) SELECT * FROM N;